- name: Configuring MongoDB server
  hosts: Mongodb
  become: yes

  vars:
    PACKAGE: mongodb-org
    SERVICE: mongod

  tasks:
  - name: Copy MongoDB repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo
  
  - name: Install MongoDB
    ansible.builtin.dnf:
      name: "{{ PACKAGE }}"
      state: present

  - name: start and enable MongoDB Service
    ansible.builtin.service:
      name: "{{ SERVICE }}"
      state: started
      enabled: yes

  - name: Allow Remote connection
    ansible.builtin.replace:
      path: /etc/mongod.conf 
      regexp: 127.0.0.1
      replace: 0.0.0.0
  
  - name: Restart Service
    ansible.builtin.service:
      name: "{{ SERVICE }}"
      state: restarted
      

