# Mongodb Configuration

- name: Configuring MongoDB
  hosts: mongodb
  become: true

  vars:
    PACKAGE: mongodb-org
  tasks:
  - name: Copy mongodb repo file
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: Install mongdb
    ansible.builtin.package:
      name: "{{ PACKAGE }}"
      state: present
  - name: Enable and Start Mongodb
    ansible.builtin.service:
       name: mongod
       enabled: yes
       state: started
  - name: Allow Remote connection
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'
  - name: Restart Mongod
    ansible.builtin.service:
      name: mongod
      state: restarted

