- name: Redis Configuration
  hosts: redis 
  become: yes

  vars:
    PACKAGE: redis

  tasks:
  - name: Disable Current Redis version
    ansible.builtin.command: dnf module disable redis -y

  - name: Enable Redis 7 version
    ansible.builtin.command: dnf module enable redis:7 -y 

  - name: Install Redis 
    ansible.builtin.dnf:
      name: "{{ PACKAGE }}"
      state: present
  

  - name: Update Remote Connection
    ansible.builtin.replace:
      path: /etc/redis/redis.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: Disable Protect mode 
    ansible.builtin.lineinfile:
      path: /etc/redis/redis.conf
      regexp: 'protected-mode'
      line: protected-mode no


  - name: Enable and start redis
    ansible.builtin.service:
      name: "{{ PACKAGE }}"
      state: started
      enabled: yes
  
  


  